USE [master]
GO
/****** Object:  Database [ATM]    Script Date: 13/2/2022 18:46:47 ******/
CREATE DATABASE [ATM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ATM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ATM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ATM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\ATM_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [ATM] SET COMPATIBILITY_LEVEL = 140
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [ATM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [ATM] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ATM] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ATM] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ATM] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ATM] SET ARITHABORT OFF 
GO
ALTER DATABASE [ATM] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ATM] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ATM] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ATM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ATM] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ATM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ATM] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ATM] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ATM] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ATM] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ATM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ATM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ATM] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [ATM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [ATM] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ATM] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ATM] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [ATM] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [ATM] SET  MULTI_USER 
GO
ALTER DATABASE [ATM] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ATM] SET DB_CHAINING OFF 
GO
ALTER DATABASE [ATM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [ATM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ATM] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [ATM] SET QUERY_STORE = OFF
GO
USE [ATM]
GO
/****** Object:  Table [dbo].[Operacion]    Script Date: 13/2/2022 18:46:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Operacion](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TarjetaId] [int] NOT NULL,
	[TipoId] [tinyint] NOT NULL,
	[Descripcion] [varchar](500) NOT NULL,
	[Fecha] [datetime] NOT NULL,
 CONSTRAINT [PK_Operacion] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Tarjeta]    Script Date: 13/2/2022 18:46:47 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Tarjeta](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Numero] [varchar](19) NOT NULL,
	[Pin] [varchar](4) NOT NULL,
	[Bloqueada] [bit] NOT NULL,
	[Balance] [bigint] NOT NULL,
	[Vencimiento] [date] NOT NULL,
	[Intentos] [int] NOT NULL,
 CONSTRAINT [PK_Tarjeta_1] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
SET IDENTITY_INSERT [dbo].[Operacion] ON 
GO
INSERT [dbo].[Operacion] ([Id], [TarjetaId], [TipoId], [Descripcion], [Fecha]) VALUES (59, 1, 1, N'Retiro: $123', CAST(N'2022-02-13T18:07:22.047' AS DateTime))
GO
INSERT [dbo].[Operacion] ([Id], [TarjetaId], [TipoId], [Descripcion], [Fecha]) VALUES (60, 1, 0, N'Balance', CAST(N'2022-02-13T18:07:43.893' AS DateTime))
GO
INSERT [dbo].[Operacion] ([Id], [TarjetaId], [TipoId], [Descripcion], [Fecha]) VALUES (61, 1, 0, N'Balance', CAST(N'2022-02-13T18:26:41.757' AS DateTime))
GO
INSERT [dbo].[Operacion] ([Id], [TarjetaId], [TipoId], [Descripcion], [Fecha]) VALUES (62, 1, 0, N'Balance', CAST(N'2022-02-13T18:29:18.293' AS DateTime))
GO
INSERT [dbo].[Operacion] ([Id], [TarjetaId], [TipoId], [Descripcion], [Fecha]) VALUES (63, 2, 0, N'Balance', CAST(N'2022-02-13T18:37:49.213' AS DateTime))
GO
INSERT [dbo].[Operacion] ([Id], [TarjetaId], [TipoId], [Descripcion], [Fecha]) VALUES (64, 2, 0, N'Balance', CAST(N'2022-02-13T18:38:14.627' AS DateTime))
GO
INSERT [dbo].[Operacion] ([Id], [TarjetaId], [TipoId], [Descripcion], [Fecha]) VALUES (65, 2, 0, N'Balance', CAST(N'2022-02-13T18:38:23.163' AS DateTime))
GO
INSERT [dbo].[Operacion] ([Id], [TarjetaId], [TipoId], [Descripcion], [Fecha]) VALUES (66, 1, 1, N'Retiro: $235', CAST(N'2022-02-13T18:44:38.213' AS DateTime))
GO
SET IDENTITY_INSERT [dbo].[Operacion] OFF
GO
SET IDENTITY_INSERT [dbo].[Tarjeta] ON 
GO
INSERT [dbo].[Tarjeta] ([Id], [Numero], [Pin], [Bloqueada], [Balance], [Vencimiento], [Intentos]) VALUES (1, N'1111-1111-1111-1111', N'1234', 0, 4418, CAST(N'2025-01-01' AS Date), 0)
GO
INSERT [dbo].[Tarjeta] ([Id], [Numero], [Pin], [Bloqueada], [Balance], [Vencimiento], [Intentos]) VALUES (2, N'2222-2222-2222-2222', N'1234', 0, 100000, CAST(N'2025-01-01' AS Date), 0)
GO
SET IDENTITY_INSERT [dbo].[Tarjeta] OFF
GO
ALTER TABLE [dbo].[Tarjeta] ADD  CONSTRAINT [DF_Tarjeta_Intentos]  DEFAULT ((0)) FOR [Intentos]
GO
ALTER TABLE [dbo].[Operacion]  WITH CHECK ADD  CONSTRAINT [FK_Operacion_Tarjeta] FOREIGN KEY([TarjetaId])
REFERENCES [dbo].[Tarjeta] ([Id])
GO
ALTER TABLE [dbo].[Operacion] CHECK CONSTRAINT [FK_Operacion_Tarjeta]
GO
USE [master]
GO
ALTER DATABASE [ATM] SET  READ_WRITE 
GO
